swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Blackfox studio Service Catalog
  description: A sample API that uses Blackfox studio Service Catalog to show the world how Organazational Models can be created with Process/Service Catalogs presented as Microservices.
  termsOfService: http://swagger.io/terms/
  contact:
    name: Blackfox Studios API Team
    email: blackfoxstudios@gmail.com
    url: http://powersbroznetwork.com
  license:
    name: MIT - Please dont steal
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: blackfoxcatalog.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /services:
    get:
      description: |
        Returns all services from the system that the user has access to from Blackfox studio to manage operations across all depatments. 
        
      operationId: findServices
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: service response
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new service in the Catalog.  Duplicates are allowed
      operationId: addService
      parameters:
        - name: service
          in: body
          description: Service to add to the Catalog
          required: true
          schema:
            $ref: '#/definitions/NewService'
      responses:
        200:
          description: service response
          schema:
            $ref: '#/definitions/Service'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /services/{id}:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the service
      operationId: find service by id
      parameters:
        - name: id
          in: path
          description: ID of service to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: service response
          schema:
            $ref: '#/definitions/Service'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single service based on the ID supplied
      operationId: deleteService
      parameters:
        - name: id
          in: path
          description: ID of service to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: service deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Service:
    allOf:
      - $ref: '#/definitions/NewService'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64
  NewService:
    required:
      - name
    properties:
      name:
        type: string
      tag:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string